---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-records-config
  namespace: default
data:
  records.txt: |-
    www.google.com A
    mail.google.com A
    chat.google.com A
    www.yahoo.com A
    www.microsoft.com A
    www.netflix.com A
    kubernetes.io A
    kube-dns.kube-system.svc.cluster.local A
    kubernetes-dashboard.kube-system.svc.cluster.local A

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dnsperf
  name: dnsperf-deployment
  namespace: default
spec:
  minReadySeconds: 3
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dnsperf
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dnsperf
    spec:
      containers:
      - env:
        - name: MAX_TEST_SECONDS
          value: "30"
        - name: MAX_QPS
          value: "100000"
        # please replace the ipaddr with the following command result output
        # $ kubectl get -n kube-system svc kube-dns -o go-template='{{.spec.clusterIP}}{{"\n"}}'
        - name: DNS_SERVER_ADDR
          value: 172.20.0.10
        image: guessi/dnsperf:alpine
        imagePullPolicy: Always
        name: dnsperf
        volumeMounts:
        - mountPath: /opt/
          name: dns-records-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: dns-records-config
        name: dns-records-volume
